services:
    audiobookbay-automated:
        image: ghcr.io/jamesry96/audiobookbay-automated:latest
        ports:
            - "5078:5078"
        container_name: audiobookbay-automated
        environment:
            - DOWNLOAD_CLIENT=${DOWNLOAD_CLIENT}
            - DL_HOST=${DL_HOST}
            - DL_PORT=${DL_PORT}
            - DL_USERNAME=${DL_USERNAME}
            - DL_PASSWORD=${DL_PASSWORD}
            - DL_CATEGORY=${DL_CATEGORY}
            - SAVE_PATH_BASE=${SAVE_PATH_BASE}
            - NAV_LINK_NAME=${NAV_LINK_NAME}
            - NAV_LINK_URL=${NAV_LINK_URL}
            - AUDIOBOOKSHELF_URL=${AUDIOBOOKSHELF_URL}
            - ABS_KEY=${ABS_KEY}
            - ABS_LIB=${ABS_LIB}
        env_file:
            - .env
